### ISSUE TITLE
task.error() gives ServerError: Job given in work result not found

### ISSUE THREAD

**Issue by sebastianbauer** [iarna/abraxas#44]
In case of error I want to use task.error() to handle this. It happens (not always), that the following error occurs. Only one worker is registered.

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
ServerError: Job given in work result not found
    at .../abraxas/client-connection.js:27:32
    at PassThrough.<anonymous> (.../node_modules/abraxas/stream-to-buffer.js:8:51)
    at PassThrough.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at PassThrough.emit (events.js:185:7)
    at endReadableNT (.../node_modules/readable-stream/lib/_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

Seems something tried to send an additional end or something.

Any suggestion for that? Thanks.

**Comment by monquixote** [comment]
I'm having the same issue
